# NumPy

### Introduction

In [1]:
import numpy as np
li_arr = [i for i in range(0,100)]
np_arr = np.arange(100)

print(li_arr)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [2]:
## Size of one element in numpy array
print(np_arr.itemsize)

## Size of 100 elements in numpy array
print(np_arr.itemsize*np_arr.size)

4
400


In [3]:
import sys

# Size of one element in list
a=10
print(sys.getsizeof(a))

# Size of 100 elements in list
print(sys.getsizeof(1)*len(li_arr))

28
2800


In [4]:
import time
import numpy as np

size = 100000

# Add elements of array a and b

def addition_using_list():
    t1 = time.time()
    a = range(size)
    b = range(size)
    c = [a[i]+b[i] for i in range(size)]
    t2 = time.time()
    return (t2-t1)

def addition_using_numpy():
    t1 = time.time()
    a = np.arange(size)
    b = np.arange(size)
    c = a + b
    t2 = time.time()
    return (t2-t1)

t_list = addition_using_list()
t_numpy = addition_using_numpy()
print('List= ',t_list*1000) ## Miliseconds
print('Numpy= ',t_numpy*1000) ## Miliseconds

List=  14.00303840637207
Numpy=  1.0013580322265625


### Why NumPy is Fast

### Create NumPy Arrays -1

In [5]:
import numpy as np
a = [1,2,3]
b = np.array(a)
print(b) 
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [6]:
a= [1,2,3,'5','a',4.5] 
b = np.array(a) # numpy can print only of same type of variable (string)
print(b) # because two element is present as string

['1' '2' '3' '5' 'a' '4.5']


In [7]:
a= [1,2,3,'5',4.5] 
b = np.array(a, dtype = int) # numpy can print only of same type of variable (string)
print(b) 

[1 2 3 5 4]


In [8]:
a= [1,2,3,'5',4.5] 
b = np.array(a, dtype = str) # numpy can print only of same type of variable (string)
print(b)

['1' '2' '3' '5' '4.5']


In [9]:
a= [1,2,3,'5',4.5] 
b = np.array(a*3) # repeat three times
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [10]:
b = np.ones(3)
b

array([1., 1., 1.])

In [11]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [12]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [13]:
b = np.ones((2,3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
b = np.zeros((3,4), dtype = float)
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
b = np.full(3,4)
b

array([4, 4, 4])

In [16]:
b = np.full((3,5),4,dtype=float)
b

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [17]:
a = np.empty(4, dtype = int)
print(a)

[-437846585 -923673024  641520277 2096132313]


### NumPy 2D Array

In [36]:
import numpy as np
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b =np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### NumPy 0s and 1s

In [37]:
import numpy as np
a = [0,0,0,0,1,0,0,0,0,0]
b =  np.array(a, dtype=int)
for i in b:
    print(i, end=" ")

0 0 0 0 1 0 0 0 0 0 

### Create NumPy Arrays -2

In [18]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b = np.arange(2,20,2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
b = np.linspace(2,10)
b

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [22]:
b = np.linspace(2,10)
b
print(b[1]-b[0])
print(b[3]-b[2])

0.16326530612244916
0.16326530612244916


In [23]:
b = np.linspace(2,10,4, dtype=int)
b

array([ 2,  4,  7, 10])

In [24]:
b = np.linspace(2,10,4, dtype=int, endpoint = False)
b

array([2, 4, 6, 8])

In [25]:
b= np.identity(3) # Only get square matrix
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
b = np.eye(3) # returns a 2D-array, which fills the diagonal, i.e. 'k' which can be set, with 1's and rest with 0's
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [28]:
b = np.random.rand(3) # range of these value from 0-1
b

array([0.82654418, 0.84675881, 0.17313313])

In [29]:
b = np.random.rand(10)*10 #range 0-10
b

array([7.29713009, 3.16521   , 9.66142384, 1.05759865, 9.61305035,
       6.75014665, 1.62535997, 5.36939971, 9.47395631, 0.64478324])

In [30]:
b = np.random.rand(2,3)
b

array([[0.45169749, 0.39468237, 0.03728587],
       [0.52080049, 0.66578596, 0.92447507]])

In [31]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

In [32]:
np.random.rand()

0.1394339205121753

In [33]:
np.random.randint(10, 4)

ValueError: low >= high

In [34]:
np.random.randint(10,size=(4,4))

array([[6, 1, 5, 7],
       [3, 3, 5, 1],
       [5, 2, 5, 7],
       [2, 9, 9, 7]])

### NumPy Inclusive

In [38]:
import numpy as np
b = np.arange(9,50, dtype=int)
for i in b:
    print(i, end=" ")

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

### Identity Matrix

In [39]:
import numpy as np
b = np.eye(5,6, dtype=int)
print(b)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


### Cut The Rope

In [56]:
import numpy as np
b = np.linspace(0,5,9)
d = np.around(b,decimals=2)
for i in range(len(d)):
    print(d[i])

0.0
0.62
1.25
1.88
2.5
3.12
3.75
4.38
5.0


### Slicing & Indexing

In [58]:
import numpy as np
li = [1,2,3,4,5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [59]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)
print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [60]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [61]:
print(li[3])
print(arr[3])
print(li[1:4])
print(arr[1:4])

4
4
[2, 3, 4]
[2 3 4]


In [62]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)
print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [63]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [64]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1])

10
10
10


In [65]:
print(li_2d[1][:3])
print(arr_2d[1,:3])

[5, 6, 7]
[5 6 7]


In [66]:
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [67]:
x= li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [68]:
print(arr_2d[0:3,2])

[ 3  7 11]


In [69]:
print(li_2d[0:3][3])

IndexError: list index out of range

In [70]:
print(arr_2d[2:4,1:3])
print(li_2d[2:4][1:3])

[[10 11]
 [14 15]]
[[13, 14, 15, 16]]


###### Output Question

In [71]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

### Print Elements

In [57]:
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)
for i in input_[2,0:3]:
    print(i, end=" ")
print()
for i in input_[1:4,3]:
    print(i,end=" ")
print()
for i in input_[2:4,0:6]:
    for j in i:
        print(j, end=" ")
print()
for i in input_[1:3,1:3]:
    for j in i:
        print(j, end=" ")
print()


11 12 13 
9 14 19 
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 


### Mathematical Operations - 1D

In [72]:
import numpy as np

li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 5 17  8 18  7]
[ 1  2 11 15  7]


In [73]:
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [74]:
a = a+1
a

array([ 6, 18,  9, 19,  8])

In [75]:
c = a+b
c

array([ 7, 20, 20, 34, 15])

In [76]:
d = a - b
d

array([ 5, 16, -2,  4,  1])

In [77]:
e = a*b
e

array([  6,  36,  99, 285,  56])

In [78]:
f = a/b
f

array([6.        , 9.        , 0.81818182, 1.26666667, 1.14285714])

In [79]:
g = a//b
g

array([6, 9, 0, 1, 1], dtype=int32)

In [80]:
h = a**b # a = [a,b,c,d] b= [i,j,k,l] h = [a^i, b^j, c^k, d^l]
h

array([          6,         324,  1316288537, -1044074789,     2097152],
      dtype=int32)

In [81]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[ 6 18  9 19  8]
60
12.0
6
0
19
3


In [82]:
print(a)
print(b)

[ 6 18  9 19  8]
[ 1  2 11 15  7]


In [83]:
a > b 

array([ True,  True, False,  True,  True])

In [84]:
a < b 

array([False, False,  True, False, False])

In [85]:
a == b

array([False, False, False, False, False])

In [86]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [88]:
print(np.logical_not(a))

[False False False False False]


In [89]:
a [2] =0
print(a)
print(np.logical_not(a))

[ 6 18  0 19  8]
[False False  True False False]


In [90]:
print(b)

[ 1  2 11 15  7]


### Boolean Indexing - 1D

In [91]:
import numpy as np

a = np.array(['t','b','r','d','e', 'f','z','a'])
b = np.random.randint(1,20,8)

print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[15  1  3 16 19 11  3  5]


In [92]:
print(b>10)

[ True False False  True  True  True False False]


In [93]:
bool_arr = b>10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr) # print that element which are satisfying the condition

[ True False False  True  True  True False False]
[15 16 19 11]


In [94]:
new_arr = b[b>10]
new_arr

array([15, 16, 19, 11])

In [95]:
new_arr = b[(b>10) & (b<18)]
new_arr 

array([15, 16, 11])

In [96]:
print(b)
c=b
c

[15  1  3 16 19 11  3  5]


array([15,  1,  3, 16, 19, 11,  3,  5])

In [97]:
c[:3] = 19
c

array([19, 19, 19, 16, 19, 11,  3,  5])

In [98]:
c[:3] = 19
c[c>15] = 100
c

array([100, 100, 100, 100, 100,  11,   3,   5])

In [99]:
c[:3] = 19
print(c)
c[c>15] = 100
c

[ 19  19  19 100 100  11   3   5]


array([100, 100, 100, 100, 100,  11,   3,   5])

In [100]:
print(b)

[100 100 100 100 100  11   3   5]


In [101]:
print(b[b==100])

[100 100 100 100 100]


In [102]:
ind = np.where(b==100)
ind

(array([0, 1, 2, 3, 4], dtype=int64),)

In [103]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100 100 100  11   3   5]


In [104]:
ind = np.where(b==100)
print(ind)
print(a[ind])

(array([0, 1, 2, 3, 4], dtype=int64),)
['t' 'b' 'r' 'd' 'e']


### Non-Zero Elements

In [105]:
import numpy as np
a = [1,2,0,0,4,0]
bool_ind= False
for i in range(5):
    if a[i]==0:
        bool_ind=False
    else:
        print(i, end=" ")

0 1 4 

### Multiples of 3

In [106]:
import numpy as np
a = [1,  3,  5,  7,  9, 11, 13, 15, 17, 19]
bool_ind= False
for i in range(9):
    if a[i]%3!=0:
        bool_ind=False
    else:
        print(i, end=" ")

1 4 7 

### Odd elements

In [107]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
bool_ind= False
for i in range(10):
    if a[i]%2!=0:
        a[i]=-1
    else:
        bool_ind= False
for i in range(10):
    print(a[i],end=" ")

-1 2 -1 4 -1 6 -1 8 -1 10 

### Replace Max

In [108]:
import numpy as np
a = [11, 2, 13, 4, 15, 6, 27, 8, 19]
bool_ind= False
for i in range(9):
    if a[i]==max(a):
        a[i]=0
        break
    else:
        bool_ind= False
for i in range(9):
    print(a[i])
    print()

11

2

13

4

15

6

0

8

19



### Negate Elements

In [109]:
import numpy as np
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
for i in range(10):
    if a[i]<3 or a[i]>8:
        print(a[i])
    else:
        print(a[i]*-1)

1
2
-3
-4
-5
-6
-7
-8
9
10


### Height

In [110]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
for i in range(20):
    if height[i]>155:
        print(age[i],height[i])
        print()

15 156

19 180

20 162

21 157

22 158

23 179

16 182

18 183

20 159

15 160

17 172



### Boolean Indexing - 2D

In [111]:
import numpy as np
a = np.random.randint(1,30,(5,6))
print(a)

[[18  6  9 21  6 10]
 [ 7 27 27 20 19  8]
 [15 23 14 22  4 12]
 [29  1 15 14  5 25]
 [12  1 15 16 12  9]]


In [112]:
a > 20

array([[False, False, False,  True, False, False],
       [False,  True,  True, False, False, False],
       [False,  True, False,  True, False, False],
       [ True, False, False, False, False,  True],
       [False, False, False, False, False, False]])

In [113]:
bool_arr=a>20
print(bool_arr)

[[False False False  True False False]
 [False  True  True False False False]
 [False  True False  True False False]
 [ True False False False False  True]
 [False False False False False False]]


In [114]:
ans=a[bool_arr]
print(ans) # 1-D array

[21 27 27 23 22 29 25]


In [116]:
b = a
print(a)

[[18  6  9 21  6 10]
 [ 7 27 27 20 19  8]
 [15 23 14 22  4 12]
 [29  1 15 14  5 25]
 [12  1 15 16 12  9]]


In [117]:
b[bool_arr]=100
print(b)

[[ 18   6   9 100   6  10]
 [  7 100 100  20  19   8]
 [ 15 100  14 100   4  12]
 [100   1  15  14   5 100]
 [ 12   1  15  16  12   9]]


In [118]:
c = np.random.randint(1,10,(2,2))
print(c)

[[7 2]
 [6 1]]


In [119]:
c_bool = np.array([[True,False],[False,True],[True,True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [120]:
print(c[c_bool])

IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 3

In [121]:
print(b)

[[ 18   6   9 100   6  10]
 [  7 100 100  20  19   8]
 [ 15 100  14 100   4  12]
 [100   1  15  14   5 100]
 [ 12   1  15  16  12   9]]


In [122]:
bool_arr = b[:,3]==100 # for column 3rd.
print(bool_arr)

[ True False  True False False]


In [123]:
b[bool_arr,3]=99 # update the column 3rd with 99.
print(b)

[[ 18   6   9  99   6  10]
 [  7 100 100  20  19   8]
 [ 15 100  14  99   4  12]
 [100   1  15  14   5 100]
 [ 12   1  15  16  12   9]]


### Sort by column

In [124]:
import numpy as np
arr=np.arange(21,1,-1).reshape(4,5)
arr=arr[arr[:,1].argsort()]
print(arr)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


### Numpy Broadcasting

In [125]:
import numpy as np

x= np.random.randint(1,10,(3,3))
y= np.random.randint(1,10,(3,3))
print(x)
print(y)

[[3 9 3]
 [1 7 4]
 [5 4 8]]
[[8 5 6]
 [9 8 2]
 [3 5 5]]


In [126]:
ans =x-y
print(ans)

[[-5  4 -3]
 [-8 -1  2]
 [ 2 -1  3]]


In [127]:
x= np.random.randint(1,10,(3,3))
y= np.random.randint(1,10,(3,))
print(x)
print(y)

[[9 7 9]
 [9 1 3]
 [5 7 4]]
[7 5 3]


In [128]:
ans = x-y
print(ans)

[[ 2  2  6]
 [ 2 -4  0]
 [-2  2  1]]


In [129]:
x= np.random.randint(1,10,(2,3))
y= np.random.randint(1,10,(3,2))
print(x)
print(y)

[[8 7 2]
 [4 4 3]]
[[6 3]
 [9 5]
 [9 4]]


In [130]:
ans = x-y # shape is not compatible
print(ans)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [131]:
y=np.transpose(y)
print(y)
ans=x-y
print(ans)

[[6 9 9]
 [3 5 4]]
[[ 2 -2 -7]
 [ 1 -1 -1]]


### Broadcasting Examples

### Example

In [132]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

for row in data:
    print(row)

{'Year': '2017', 'Month': '1', 'Day': '2', 'Country': 'Afghanistan', 'Region': 'South Asia', 'city': 'Takhta Pul', 'latitude': '31.320556', 'longitude': '65.961111', 'AttackType': 'Hostage Taking (Kidnapping)', 'Killed': '0.0', 'Wounded': '0.0', 'Target': 'Construction Workers', 'Group': 'Taliban', 'Target_type': 'Business', 'Weapon_type': 'Firearms', 'casualities': '0.0'}
{'Year': '2017', 'Month': '1', 'Day': '3', 'Country': 'Sudan', 'Region': 'Sub-Saharan Africa', 'city': 'Fantaga', 'latitude': '12.921007000000001', 'longitude': '24.318324', 'AttackType': 'Armed Assault', 'Killed': '2.0', 'Wounded': '0.0', 'Target': 'Civilians: Haroun Yousif, Hamid Ibrahim', 'Group': 'Unknown', 'Target_type': 'Private Citizens & Property', 'Weapon_type': 'Firearms', 'casualities': '2.0'}
{'Year': '2017', 'Month': '1', 'Day': '1', 'Country': 'Democratic Republic of the Congo', 'Region': 'Sub-Saharan Africa', 'city': 'Saboko', 'latitude': '1.452372', 'longitude': '29.875162', 'AttackType': 'Armed Assau

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [133]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
    
np_killed= np.array(killed)
np_wounded=np.array(wounded)
np_killed

array(['0.0', '2.0', '7.0', ..., '0.0', '0.0', '0.0'], dtype='<U5')

In [134]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
    
np_killed= np.array(killed)
np_wounded=np.array(wounded)
np_wounded

array(['0.0', '0.0', '0.0', ..., '0.0', '0.0', '0.0'], dtype='<U5')

In [135]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
    
np_killed= np.array(killed)
np_wounded=np.array(wounded)
np_killed==''

array([False, False, False, ..., False, False, False])

In [136]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
    
np_killed= np.array(killed)
np_wounded=np.array(wounded)

np_killed[np_killed=='']

array(['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
       '', '', '', '', ''

In [138]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
    
np_killed= np.array(killed)
np_wounded=np.array(wounded)

np_killed[np_killed==''] = '0.0'
np_killed

array(['0.0', '2.0', '7.0', ..., '0.0', '0.0', '0.0'], dtype='<U5')

In [140]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
    
np_killed= np.array(killed)
np_wounded=np.array(wounded)

np_killed[np_killed==''] = '0.0'
np_wounded[np_wounded == '']='0.0'

np_killed = np.array(np_killed,dtype=float)
np_wounded = np.array(np_wounded,dtype=float)

killed_wounded=np_killed+np_wounded
killed_wounded

array([0., 2., 7., ..., 0., 0., 0.])

In [141]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
    
np_killed= np.array(killed)
np_wounded=np.array(wounded)

np_killed[np_killed==''] = '0.0'
np_wounded[np_wounded == '']='0.0'

np_killed = np.array(np_killed,dtype=float)
np_wounded = np.array(np_wounded,dtype=float)

killed_wounded=np_killed+np_wounded
np_country = np.array(country)

np_country[np_country=='India']

array(['India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'India', 'India', 'India', 'India', 'India', 'India',
       'India', 'Ind

In [142]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
    
np_killed= np.array(killed)
np_wounded=np.array(wounded)

np_killed[np_killed==''] = '0.0'
np_wounded[np_wounded == '']='0.0'

np_killed = np.array(np_killed,dtype=float)
np_wounded = np.array(np_wounded,dtype=float)

killed_wounded=np_killed+np_wounded
np_country = np.array(country)

bool_arr=np_country=='India'
killed_wounded[bool_arr]

array([ 0.,  1.,  4.,  1.,  1.,  0.,  2.,  2.,  0.,  1.,  2.,  2.,  1.,
        0.,  1.,  4.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  4.,  1.,  2.,
        1.,  0.,  5.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  7.,  0.,  1.,
        0.,  0.,  0.,  0.,  0.,  4.,  0., 95.,  0.,  2.,  0.,  1.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  2.,  0.,  1.,  1., 18.,  2., 13.,  1.,
        0.,  3.,  0.,  1.,  0.,  0.,  0.,  1.,  1., 10.,  0.,  0.,  1.,
        1.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  2.,  1.,  0.,  4.,
        0.,  0.,  0.,  0.,  0.,  1.,  0.,  5.,  2.,  0.,  0.,  0.,  2.,
        1.,  2.,  0.,  0.,  0.,  0.,  1.,  1.,  4.,  1.,  0.,  0.,  1.,
        1.,  1.,  9.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
        0.,  8.,  0.,  0.,  0.,  0.,  0.,  2.,  0.,  0.,  0.,  0.,  1.,
        0.,  3.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  1.,  1.,  0

In [162]:
import numpy as np
import csv
file_obj=open('year2017.csv')
data=csv.DictReader(file_obj,skipinitialspace=True)

killed=[]
wounded=[]
country=[]

for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
    wounded.append(row['Wounded'])
    
np_killed= np.array(killed)
np_wounded=np.array(wounded)

np_killed[np_killed==''] = '0.0'
np_wounded[np_wounded == '']='0.0'

np_killed = np.array(np_killed,dtype=float)
np_wounded = np.array(np_wounded,dtype=float)
np_killed = np.array(np_killed,dtype=int)
np_wounded = np.array(np_wounded,dtype=int)
killed_wounded=np_killed+np_wounded
np_country = np.array(country)

bool_arr=np_country=='India'
ans=killed_wounded[bool_arr]
print(np.sum(ans))
print(np.sum(killed_wounded))

1167
51372


### Killed in USA

In [180]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
import csv
file_obj=open('terrorismData.csv', 'r', encoding='utf-8')
data=csv.DictReader(file_obj,skipinitialspace=True)
killed=[]
country=[]
for row in data:
    killed.append(row['Killed'])
    country.append(row['Country'])
np_killed= np.array(killed)
np_killed[np_killed==''] = '0.0'
np_killed = np.array(np_killed,dtype=float)
np_killed = np.array(np_killed,dtype=int)
np_country = np.array(country)
bool_arr=np_country=='United States'
ans=np_killed[bool_arr]
for i in range(len(ans)):
    print(ans[i])
    print()


0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

1

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

2

0

0

0

0

0

0

2

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

1

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

1

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

1

0

0

0

0

0

0

0

0

0

0

0

1

0

0

0

0

0

0

0

1

0

0

0

0

0

0

0

1

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

1

1

0

0

0

0

0

0

0

1

0

0

0

0

0

0

0

0

0

0

0

0

0

1

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

0

1

0

0

0

0

0

0

2

### Terrorism Day

In [183]:
import numpy as np
import csv
file_obj=open('terrorismData.csv', 'r', encoding='utf-8')
data=csv.DictReader(file_obj,skipinitialspace=True)
day=[]
count=0
for row in data:
    day.append(row['Day'])
np_day= np.array(day)
np_day = np.array(np_day,dtype=float)
np_day = np.array(np_day,dtype=int)
for i in range(len(np_day)):
    if np_day[i]>=10 and np_day[i]<=20:
        count+=1
print(count)

66330


### Terrorism Date

In [1]:
import numpy as np
import csv
file_obj=open('terrorismData.csv', 'r', encoding='utf-8')
data=csv.DictReader(file_obj,skipinitialspace=True)
day=[]
month=[]
year=[]
count=0
for row in data:
    day.append(row['Day'])
    month.append(row['Month'])
    year.append(row['Year'])
np_day= np.array(day)
np_month=np.array(month)

np_year=np.array(year)
np_day = np.array(np_day,dtype=float)
np_day = np.array(np_day,dtype=int)
for i in range(len(np_month)):
    if np_year[i]=='2010':
        if np_month[i]=='1':
            if (np_day[i]>=1) & (np_day[i]<=31):
                count+=1
print(count)

271


### Terror Casualty Attack

In [2]:
import numpy as np
import csv
with open('terrorismData.csv', encoding = "utf-8") as file_obj:
    file_data=csv.DictReader(file_obj,skipinitialspace=True)
    wounded=[]
    killed=[]
    grp=[]
    city=[]
    for row in file_data:
        if row['Year']=='1999':
             if row["Month"]=="5" or row["Month"]=="6" or row["Month"]=="7":
                    if row['State']=='Jammu and Kashmir':
                            if "Unknown" not in row["City"]:
                                if "Unknown" not in row["Group"]:
                                    killed.append(row['Killed'])
                                    wounded.append(row['Wounded'])
                                    city.append(row['City'])
                                    grp.append(row['Group'])
killed = np.array(killed)
wounded = np.array(wounded)
city = np.array(city)
grp=np.array(grp)
 
killed[killed == ""] = "0.0"
wounded[wounded == ""] = "0.0"
killed = np.array(killed, dtype = float)
wounded = np.array(wounded, dtype = float)
# taking sum and then printing the required values
casualty = (killed + wounded)
max_casualty = (int)(casualty.max())
# getting the INDEX of max casualty, this is for putting the required index in city and group
max_casualty_arg = casualty.argmax() #argmax gives index
print(max_casualty,city[max_casualty_arg],grp[max_casualty_arg])

22 Kargil District Separatists


### Terror Casualty Red

In [4]:
import numpy as np
import csv
file_obj=open('terrorismData.csv',encoding = "utf-8")
data=csv.DictReader(file_obj,skipinitialspace=True)
killed=[]
wounded=[]
for row in data:
    if row['State']=='Jharkhand' or row['State']=='Odisha' or row['State']=='Andhra Pradesh'or row['State']=='Chhattisgarh':
        killed.append(row['Killed'])
        wounded.append(row['Wounded'])
np_killed=np.array(killed)
np_wounded=np.array(wounded)
np_killed[np_killed=='']='0.0'
np_wounded[np_wounded=='']='0.0'
np_killed=np.array(np_killed,dtype=float)
np_wounded=np.array(np_wounded,dtype=float)
print(int(np.sum(np_killed)+np.sum(np_wounded)))

5628


### Terror City Casualty

In [5]:
## Open and read data file as specified in the question
## Print the required output in given format
import csv
import numpy as np
path='terrorismData.csv'
casualty=[]
city=[]
## Here we filter out the data
with open(path, 'r',encoding='ISO-8859-1') as data:
    reader = csv.DictReader(data)
    for row in reader:
        if row['Country']=='India':
            city.append(row['City'])
            casualty.append([row['Killed'],row['Wounded']])
npcasualty=np.array(casualty)
npcity=np.array(city)
## Coverting the empty values present in Killed and wounded feature to Zero
npcasualty[npcasualty=='']=0
## Converting the string value to float
npcasualty=np.array(npcasualty,dtype=float)
## Now Summing up the Killed and wounded feature to find out the casualty
npcasualty=np.sum(npcasualty,axis=1)

def cityCasualty(cityarr,casualtyarr):
    arr=[]
    unique=np.unique(cityarr)
    for i in unique:
        index=np.where(cityarr==i)
        sumCasualty= casualtyarr[index].sum()
        arr.append([sumCasualty,i])
    arr.sort(reverse=True)
    return arr

arr=cityCasualty(npcity,npcasualty)
for i in range(6):
    if arr[i][1]!='Unknown':
        print(arr[i][1],int(arr[i][0]))

Srinagar 3134
New Delhi 2095
Mumbai 2016
Jammu 1119
Guwahati 822


### Terrorism FrequentDay

In [8]:
import numpy as np
import csv
file_obj=open('terrorismData.csv','r',encoding='ISO-8859-1')
data=csv.DictReader(file_obj,skipinitialspace=True)
day=[]
for row in data:
    day.append(row['Day'])
np_day=np.array(day)
unique,count=np.unique(np_day,return_counts=True)
index=count.argmax()
print(unique[index],count[index])

15 6500


###### Thank You